# SPDX-FileCopyrightText: 2023 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name = "bmm150_examples"
description = "Examples for bmm150 magnitometr"
version = "1.0.0"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/bmm150"
tags = ["sensor", "humidity", "temperature", "pressure", "driver"]
project-files = ["bmm150_put/bmm150_put.gpr", "bmm150_lcd/bmm150_lcd.gpr", "bmm150_spi/bmm150_spi.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = false

[[depends-on]]
gnat_arm_elf = "*"
bmm150 = "*"
blinky_stm32_f4ve = "*"

[[pins]]
bmm150 = { path='..' }
blinky_stm32_f4ve = { url='https://github.com/AdaCore/Ada_Drivers_Library', subdir='examples/stm32_f4ve' }
